// Generated by CoffeeScript 1.6.2
var expect, fs, rimraf, spawn;

expect = require('expect.js');

fs = require('fs');

rimraf = require('rimraf');

spawn = require('child_process').spawn;

describe('parachute', function() {
  var binPath, clean, cwd, testDir;

  binPath = "" + __dirname + "/../bin/parachute";
  cwd = process.cwd();
  testDir = "" + __dirname + "/install_test";
  process.env['HOME'] = testDir;
  clean = function(done) {
    return rimraf(testDir, function(err) {
      if (err) {
        throw new Error('Unable to remove install directory');
      }
      return typeof done === "function" ? done() : void 0;
    });
  };
  beforeEach(function(done) {
    process.chdir(cwd);
    return clean(function() {
      return fs.mkdir(testDir, function(err) {
        if (err) {
          throw err;
        }
        process.chdir(testDir);
        return typeof done === "function" ? done() : void 0;
      });
    });
  });
  after(function(done) {
    process.chdir(cwd);
    return clean(done);
  });
  return it('exits with status code 0 if there were no errors', function(done) {
    var cp,
      _this = this;

    cp = spawn('node', [binPath, '-v'], {
      cwd: testDir
    });
    return cp.on('exit', function(status) {
      expect(status).to.eql(0);
      return done();
    });
  });
});
