// Generated by CoffeeScript 1.6.2
var EventEmitter, expect, help;

EventEmitter = require('events').EventEmitter;

expect = require('expect.js');

help = require('../lib/commands/help');

describe('help', function() {
  it('returns an emitter', function() {
    return expect(help() instanceof EventEmitter).to.be(true);
  });
  it('emits an end event', function(done) {
    return help().on('end', function(data) {
      expect(data).to.be.ok();
      return done();
    });
  });
  return it('emits an end event with data string', function(done) {
    return help().on('end', function(data) {
      expect(data).to.be.a('string');
      return done();
    });
  });
});
