// Generated by CoffeeScript 1.6.2
var expect, fs, rimraf, spawn;

expect = require('expect.js');

fs = require('fs');

rimraf = require('rimraf');

spawn = require('child_process').spawn;

describe('version', function() {
  var binPath;

  binPath = "" + __dirname + "/../bin/parachute";
  return it('prints the version', function(done) {
    var cp, pkg,
      _this = this;

    pkg = require('../package.json');
    cp = spawn('node', [binPath, '-v']);
    return cp.stdout.on('data', function(data) {
      expect(data.toString()).to.contain(pkg.version);
      return done();
    });
  });
});
