// Generated by CoffeeScript 1.6.2
var config, fs, spawn;

fs = require('fs');

spawn = require('child_process').spawn;

config = require('../core/config');

module.exports = function(args, options) {
  var child;

  options = options || {};
  options = {
    cwd: options.cwd || process.cwd()
  };
  child = spawn('git', args, options);
  child.stderr.on('data', function(data) {
    return console.log("\n" + (data.toString()));
  });
  child.on('exit', function(code) {
    if (code === 128) {
      return console.log("git did not exit cleanly!");
    }
  });
  return child;
};
