// Generated by CoffeeScript 1.6.2
var colors, hogan, nopt, _;

colors = require('colors');

hogan = require('hogan.js');

_ = require('lodash');

nopt = require('nopt');

module.exports = hogan.Template.prototype.renderWithColors = function(context, partials, indent) {
  context = _.extend({
    yellow: function(s) {
      return s.yellow;
    },
    green: function(s) {
      return s.green;
    },
    cyan: function(s) {
      return s.cyan;
    },
    red: function(s) {
      return s.red;
    },
    white: function(s) {
      return s.white;
    }
  }, context);
  return this.ri([context], partials || {}, indent);
};
