// Generated by CoffeeScript 1.6.2
var _;

_ = require('lodash/dist/lodash.compat');

_.mixin({
  endsWith: function(str, suffix) {
    return str.indexOf(suffix, str.length - suffix.length) !== -1;
  },
  lpad: function(num, digits) {
    var str;

    str = num.toString();
    return Array(digits - str.length + 1).join('0') + str;
  }
});

module.exports = _;
