// Generated by CoffeeScript 1.6.2
var _;

_ = require('../util/lodash-ext');

module.exports = {
  dirName: function() {
    var dirs;

    dirs = process.cwd().split('/');
    return dirs[dirs.length - 1];
  },
  month: function() {
    return _.lpad((new Date).getMonth() + 1, 2);
  },
  day: function() {
    return _.lpad((new Date).getDate(), 2);
  },
  year: function() {
    return (new Date).getFullYear();
  },
  date: function() {
    var me;

    me = module.exports;
    return "" + (me.year()) + "-" + (me.month()) + "-" + (me.day());
  }
};
