// Generated by CoffeeScript 1.6.2
var cacheDir, config, cwd, dependencies, fs, home, jsonPath, mkdirp, path, scripts;

fs = require('fs');

mkdirp = require('mkdirp');

path = require('path');

cwd = process.cwd();

home = process.env['HOME'];

cacheDir = path.join(home, '.parachute');

if (!fs.existsSync(cacheDir)) {
  mkdirp(cacheDir);
}

jsonPath = path.join(cwd, 'parachute.json');

dependencies = [];

scripts = {};

if (fs.existsSync(jsonPath)) {
  dependencies = dependencies.concat(require(jsonPath).dependencies);
  scripts = require(jsonPath).scripts;
}

config = {
  cacheDir: cacheDir,
  dependencies: dependencies,
  options: {
    scripts: scripts
  }
};

module.exports = config;
