// Generated by CoffeeScript 1.6.2
var events, fs, hogan, path, templates;

events = require('events');

hogan = require('hogan.js');

path = require('path');

fs = require('fs');

require('../util/hogan-colors');

templates = {};

module.exports = function(name, context, sync) {
  var emitter, templateName, templatePath;

  emitter = new events.EventEmitter;
  templateName = name + '.mustache';
  templatePath = path.join(__dirname, '../../templates/', templateName);
  if (sync) {
    if (!templates[templatePath]) {
      templates[templatePath] = fs.readFileSync(templatePath, 'utf-8');
    }
    return hogan.compile(templates[templatePath]).renderWithColors(context);
  } else if (templates[templatePath]) {
    process.nextTick(function() {
      return emitter.emit('data', hogan.compile(templates[templatePath]).renderWithColors(context));
    });
  } else {
    fs.readFile(templatePath, 'utf-8', function(err, file) {
      if (err) {
        return emitter.emit('error', err);
      }
      templates[templatePath] = file;
      return emitter.emit('data', hogan.compile(file).renderWithColors(context));
    });
  }
  return emitter;
};
