// Generated by CoffeeScript 1.6.2
var EventEmitter, nopt, template;

EventEmitter = require('events').EventEmitter;

nopt = require('nopt');

template = require('../util/template');

module.exports = function(name) {
  var emitter, templateName;

  emitter = new EventEmitter;
  templateName = name != null ? "help-" + name : 'help';
  template(templateName).on('data', emitter.emit.bind(emitter, 'end'));
  return emitter;
};

module.exports.line = function(argv) {
  var options;

  options = nopt(null, null, argv);
  return module.exports(options.argv.remain.slice(1)[0]);
};
