// Generated by CoffeeScript 1.6.2
var Dependency, EventEmitter, Manager, config, help, nopt, optionTypes, shorthand, _;

EventEmitter = require('events').EventEmitter;

Manager = require('../core/manager');

Dependency = require('../core/dependency');

config = require('../core/config');

help = require('../commands/help');

nopt = require('nopt');

_ = require('../util/lodash-ext');

optionTypes = {
  help: Boolean
};

shorthand = {
  h: ['--help']
};

module.exports = function(dependencies, options) {
  var emitter, manager;

  emitter = new EventEmitter;
  manager = new Manager(dependencies, options);
  manager.on('error', emitter.emit.bind(emitter, 'error')).on('updated', function() {
    return emitter.emit('end', 0);
  }).update();
  return emitter;
};

module.exports.line = function(argv) {
  var options;

  options = _.extend(nopt(optionTypes, shorthand, argv), config.options);
  if (options.help) {
    return help('update');
  } else {
    return module.exports(config.dependencies, options);
  }
};
